export const TEST_IDS = {
  auth: {
    dashboard: 'auth.dashboard',
    emailInput: 'auth.email-input',
    loginTab: 'auth.login-tab',
    logoutButton: 'auth.logout-button',
    nameInput: 'auth.name-input',
    passwordInput: 'auth.password-input',
    registerTab: 'auth.register-tab',
    screen: 'auth.screen',
    socialAppleButton: 'auth.social-apple-button',
    socialGoogleButton: 'auth.social-google-button',
    submitButton: 'auth.submit-button',
    userEmail: 'auth.user-email',
  },
  approval: {
    email: 'approval.email',
    recheckButton: 'approval.recheck-button',
    screen: 'approval.screen',
    status: 'approval.status',
  },
  appointment: {
    placeholder: 'appointment.placeholder',
    screen: 'appointment.screen',
  },
  profile: {
    screen: 'profile.screen',
    languageGroup: 'profile.language-group',
    languageOption: 'profile.language-option',
    languageSection: 'profile.language-section',
    specialtyError: 'profile.specialty-error',
    specialtyGroup: 'profile.specialty-group',
    specialtyMissing: 'profile.specialty-missing',
    specialtyOption: 'profile.specialty-option',
    specialtySaveButton: 'profile.specialty-save-button',
    specialtySection: 'profile.specialty-section',
  },
  screen: {
    backButton: 'screen.back-button',
  },
  tabs: {
    appointmentTab: 'tabs.appointment',
    profileTab: 'tabs.profile',
  },
} as const;
