export const TEST_IDS = {
  auth: {
    dashboard: 'auth.dashboard',
    emailInput: 'auth.email-input',
    loginTab: 'auth.login-tab',
    logoutButton: 'auth.logout-button',
    nameInput: 'auth.name-input',
    passwordInput: 'auth.password-input',
    registerTab: 'auth.register-tab',
    screen: 'auth.screen',
    socialAppleButton: 'auth.social-apple-button',
    socialGoogleButton: 'auth.social-google-button',
    submitButton: 'auth.submit-button',
    userEmail: 'auth.user-email',
  },
  approval: {
    email: 'approval.email',
    recheckButton: 'approval.recheck-button',
    screen: 'approval.screen',
    status: 'approval.status',
  },
  appointment: {
    screen: 'appointment.screen',
    patientNameInput: 'appointment.patient-name-input',
    startButton: 'appointment.start-button',
    stopButton: 'appointment.stop-button',
    newButton: 'appointment.new-button',
    timer: 'appointment.timer',
    status: 'appointment.status',
    error: 'appointment.error',
    medCard: {
      section: 'appointment.medcard-section',
      sendToMisButton: 'appointment.medcard-send-to-mis-button',
      deliveryStatus: 'appointment.medcard-delivery-status',
      deliveryError: 'appointment.medcard-delivery-error',
    },
  },
  profile: {
    screen: 'profile.screen',
    languageGroup: 'profile.language-group',
    languageOption: 'profile.language-option',
    languageSection: 'profile.language-section',
    specialtyError: 'profile.specialty-error',
    specialtyGroup: 'profile.specialty-group',
    specialtyMissing: 'profile.specialty-missing',
    specialtyOption: 'profile.specialty-option',
    specialtySaveButton: 'profile.specialty-save-button',
    specialtySection: 'profile.specialty-section',
    misCodeSection: 'profile.mis-code-section',
    misCodeValue: 'profile.mis-code-value',
    misCodeError: 'profile.mis-code-error',
    misCodeRegenerateButton: 'profile.mis-code-regenerate-button',
  },
  screen: {
    backButton: 'screen.back-button',
  },
  tabs: {
    appointmentTab: 'tabs.appointment',
    profileTab: 'tabs.profile',
  },
} as const;
